training:
  LogisticRegression:
    penalty:
    - l1
    - l2
    C:
    - 0.1
    - 1.0
    solver:
    - liblinear
    - lbfgs
    max_iter:
    - 100
    - 200
    random_state:
    - 42
    - 123
base_model_score: '0.7586'
